context.modules = [
    {
        name = libpipewire-module-loopback
        args = {
            node.description = "Game Audio"
            audio.position = [ FL FR ]
            capture.props = {
                node.name = "game-audio-sink"
                media.class = "Audio/Sink"
                node.description = "Game Audio"
                # Make it selectable in desktop audio controls
                device.description = "Game Audio"
                device.class = "sound"
                device.icon-name = "audio-card"
                node.virtual = false
            }
            playback.props = {
                node.name = "game-audio-output"
                target.object = "alsa_output.usb-Roland_Rubix22-00.analog-stereo"
                node.passive = true
            }
        }
    }
    # {
    #     name = libpipewire-module-loopback
    #     args = {
    #         node.description = "Voice Chat Audio"
    #         audio.position = [ FL FR ]
    #         capture.props = {
    #             node.name = "voice-chat-sink"
    #             media.class = "Audio/Sink"
    #             node.description = "Voice Chat Audio"
    #             # Make it selectable in desktop audio controls
    #             device.description = "Voice Chat Audio"
    #             device.class = "sound"
    #             device.icon-name = "audio-card"
    #             node.virtual = false
    #         }
    #         playback.props = {
    #             node.name = "voice-chat-output"
    #             target.object = "alsa_output.pci-0000_00_1b.0.analog-stereo"
    #             node.passive = true
    #         }
    #     }
    # }
]