context.objects = [
    {
        factory = adapter
        args = {
            factory.name = support.null-audio-sink
            node.name = "Mic FX"
            node.description = "Microphone FX settings"
            media.class = Audio/Duplex
            audio.position = [ MONO ]
            # Desktop integration properties for user selection
            device.description = "Microphone FX settings"
            device.class = "sound"
            device.icon-name = "audio-card"
            node.virtual = true
            # # Monitor configuration optimized for VST routing
            monitor.channel-volumes = true
            monitor.passthrough = true
            # adapter.auto-port-config = {k
            #     mode = dsp
            #     monitor = truetttttt21
            #     position = preserve
            # }
        }
    }
]