theme {
  style = Fusion
  color_scheme = /home/aaron/.local/share/color-schemes/Carl.colors
  icon_theme = Papirus-Dark
  font = Segoe UI
  font_size = 10
  font_fixed = Consolas
  font_fixed_size = 10
}
