# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Autostart Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

source = ~/.config/hypr/config/defaults.conf

# Autostart wiki https://wiki.hyprland.org/Configuring/Keywords/#executing

#Gotm from https://github.com/retrilzzy/dotfiles/blob/main/Configs/.config/hypr/hyprland/autostart.conf
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --all
exec-once = sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = uwsm app -- wl-clip-persist --clipboard regular --write-timeout 1000 --selection-size-limit 2097152 --all-mime-type-regex '(?i)^(?!(?:image|audio|video|font|model)/|x-kde-passwordManagerHint).+'


#exec-once = swaybg -o \* -i /usr/share/wallpapers/cachyos-wallpapers/Skyscraper.png -m fill
#exec-once = quickshell &
#exec-once = fcitx5 -d &
#exec-once = swaync &
#exec-once = nm-applet --indicator &
#exec-once = bash -c "mkfifo /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob && tail -f /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob | wob & disown" &

# ## Slow app launch fix
#exec-once = systemctl --user import-environment &
#exec-once = hash dbus-update-activation-environment 2>/dev/null &
#exec-once = dbus-update-activation-environment --systemd &

# ## Idle configuration
#exec-once = $idlehandler
