# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛


# General
$filemanager = dolphin
#$applauncher = rofi -modi drun,calc,window,emoji -sidebar-mode -show drun -show-icons -no-show-match -no-history -no-sort -calc-command "echo -n '{result}' | xclip -sel c"\
 #   -kb-element-next ''\
  #  -kb-element-previous ''\
   # -kb-mode-next 'Tab'\
   # -kb-mode-previous 'Shift+Tab'
$applauncher = rofi-la
$terminal = kitty #ghostty #alacritty
$idlehandler = swayidle -w timeout 300 'swaylock -f -c 000000' before-sleep 'swaylock -f -c 000000'

# Screenshots
$shot-region = grimblast --notify copy area
$shot-window = grimblast copy active
$shot-screen = grimblast copy output
