# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Monitor Configuration                   ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Monitor wiki https://wiki.hyprland.org/Configuring/Monitors/

#monitor = , preferred, auto, 1
#monitor = HDMI-A-1, 1920x1080@144,auto,1,cm,hdr
monitorv2 {
  output = HDMI-A-1
  mode = 1920x1080@144
  position = auto
  scale = 1
  cm = auto
  sdrbrightness = 1.2
  sdrsaturation = 0.98
  sdr_min_luminance = 0.005 
  sdr_max_luminance = 400
  supports_wide_color = true
  supports_hdr = true

}
# experimental {
#  hdr = true
#   xx_color_management_v4 = true
#   wide_color_gamut = true
# }

# If you need to scale things like steam etc, please uncomment these lines.
#xwayland {
 # force_zero_scaling = true       # Unscale XWaylandFez
#}

# Adjust GDK_SCALE accordingly to your liking.
#env = GDK_SCALE, 2                # GDK Scaling Factor (no fractional scaling)

# Electron based apps use X11 as default, auto should detect wayland
#env = ELECTRON_OZONE_PLATFORM_HINT, auto
